FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

RUN CGO_ENABLED=0 GOOS=linux go build -o api-exec main.go

FROM alpine:latest
RUN apk --no-cache dd ca-certificate

WORKDIR /root/

COPY --from=builder /app/api-exec .

EXPOSE 8080

CMD ["./api-exec"]